language: php

php:
  - '5.6'
  - '7.1'
  - '7.2'

before_script:
  - composer install -n

script:
  - php vendor/bin/phpunit

after_success:
  - php vendor/bin/codacycoverage clover tests/_reports/logs/clover.xml