language: php

php:
  - '5.6'
  - '7.2'
  - '7.3'

before_script:
  - composer install

script:
  - php vendor/bin/phpunit

after_success:
  - php vendor/bin/codacycoverage clover tests/_reports/logs/clover.xml